stages:
  - package
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

package_pd_deken:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH  
    - if: $CI_COMMIT_TAG != ''  
  stage: package
  script:
    - mkdir -p build/$CI_PROJECT_NAME
    - cp -r ex readme.md license.txt $CI_PROJECT_DIR/*.pd build/$CI_PROJECT_NAME || true
    - deken package build/$CI_PROJECT_NAME --version $CI_COMMIT_TAG
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$CI_PROJECT_NAME*.dek*
    expire_in: 24h

push_github:
    stage: deploy
    script:
        - git remote add github https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git || true
        # we need some extra treatment because the gitlab-runner doesn't check out the full history
        - git push github HEAD:master --tags

upload_deken:
    stage: deploy
    dependencies:
        - package_pd_deken
    script:
        - deken upload --no-source-error $CI_PROJECT_DIR/$CI_PROJECT_NAME*.dek

upload_owncloud:
    stage: deploy
    dependencies:
        - package_pd_deken
    script:
        - oc-upload.sh pdmax-packages $CI_PROJECT_DIR/$CI_PROJECT_NAME*.dek* $CI_PROJECT_DIR/$CI_PROJECT_NAME-*.zip
